### ISSUE TITLE
tier_2 data handling

### ISSUE THREAD

**Issue by sunny-bak** [ecmwf-projects/mooc-machine-learning-weather-climate#6]
Hello,
I am working on tier_2/data_handling/04-dataset-plugin.ipynb, and noticed a possible typo in one of the text cell.  
plugin_plugin_dataset to be changed to plugin_create_dateset or plugin_create_source?

```
Run from a shell terminal:
$ climetlab
(climetlab) plugin_plugin_dataset
Answer questions...

```

**Comment by floriankrb** [comment]
indeed, thanks for reporting, this is now fixed!
